// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessAPI.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LeaderboardEntry
    {
        /// <summary>
        /// Initializes a new instance of the LeaderboardEntry class.
        /// </summary>
        public LeaderboardEntry() { }

        /// <summary>
        /// Initializes a new instance of the LeaderboardEntry class.
        /// </summary>
        public LeaderboardEntry(int? id = default(int?), string username = default(string), bool? humanWon = default(bool?), string gameTime = default(string))
        {
            ID = id;
            Username = username;
            HumanWon = humanWon;
            GameTime = gameTime;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public int? ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "humanWon")]
        public bool? HumanWon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gameTime")]
        public string GameTime { get; set; }

    }
}
