// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Cell
    {
        /// <summary>
        /// Initializes a new instance of the Cell class.
        /// </summary>
        public Cell() { }

        /// <summary>
        /// Initializes a new instance of the Cell class.
        /// </summary>
        public Cell(Piece mPiece = default(Piece), int? mRow = default(int?), int? mCol = default(int?))
        {
            MPiece = mPiece;
            MRow = mRow;
            MCol = mCol;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_piece")]
        public Piece MPiece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_row")]
        public int? MRow { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_col")]
        public int? MCol { get; set; }

    }
}
