// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LeaderboardEntry
    {
        /// <summary>
        /// Initializes a new instance of the LeaderboardEntry class.
        /// </summary>
        public LeaderboardEntry() { }

        /// <summary>
        /// Initializes a new instance of the LeaderboardEntry class.
        /// </summary>
        public LeaderboardEntry(string id = default(string), string description = default(string), string type = default(string), string owner = default(string))
        {
            ID = id;
            Description = description;
            Type = type;
            Owner = owner;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ID")]
        public string ID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Owner")]
        public string Owner { get; set; }

    }
}
