// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Move
    {
        /// <summary>
        /// Initializes a new instance of the Move class.
        /// </summary>
        public Move() { }

        /// <summary>
        /// Initializes a new instance of the Move class.
        /// </summary>
        public Move(Cell mStartCell = default(Cell), Cell mEndCell = default(Cell), Piece mPiece = default(Piece), Piece mCapturedPiece = default(Piece), Piece mPromoPiece = default(Piece), Piece mEnPassantPiece = default(Piece), int? mType = default(int?), bool? mCauseCheck = default(bool?), int? mScore = default(int?))
        {
            MStartCell = mStartCell;
            MEndCell = mEndCell;
            MPiece = mPiece;
            MCapturedPiece = mCapturedPiece;
            MPromoPiece = mPromoPiece;
            MEnPassantPiece = mEnPassantPiece;
            MType = mType;
            MCauseCheck = mCauseCheck;
            MScore = mScore;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_StartCell")]
        public Cell MStartCell { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_EndCell")]
        public Cell MEndCell { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_Piece")]
        public Piece MPiece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_CapturedPiece")]
        public Piece MCapturedPiece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_PromoPiece")]
        public Piece MPromoPiece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_EnPassantPiece")]
        public Piece MEnPassantPiece { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_Type")]
        public int? MType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_CauseCheck")]
        public bool? MCauseCheck { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_Score")]
        public int? MScore { get; set; }

    }
}
