// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Piece
    {
        /// <summary>
        /// Initializes a new instance of the Piece class.
        /// </summary>
        public Piece() { }

        /// <summary>
        /// Initializes a new instance of the Piece class.
        /// </summary>
        public Piece(int? mMoves = default(int?), Side mSide = default(Side), int? mType = default(int?))
        {
            MMoves = mMoves;
            MSide = mSide;
            MType = mType;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_moves")]
        public int? MMoves { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_side")]
        public Side MSide { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_type")]
        public int? MType { get; set; }

    }
}
