// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Side
    {
        /// <summary>
        /// Initializes a new instance of the Side class.
        /// </summary>
        public Side() { }

        /// <summary>
        /// Initializes a new instance of the Side class.
        /// </summary>
        public Side(int? mSide = default(int?))
        {
            MSide = mSide;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "m_side")]
        public int? MSide { get; set; }

    }
}
