// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace MagiciansChessApp
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for ChessAI.
    /// </summary>
    public static partial class ChessAIExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='gameXml'>
            /// </param>
            /// <param name='timeLimitInSecs'>
            /// </param>
            public static string PostByGamexmlAndTimelimitinsecs(this IChessAI operations, StringAux gameXml, int timeLimitInSecs)
            {
                return Task.Factory.StartNew(s => ((IChessAI)s).PostByGamexmlAndTimelimitinsecsAsync(gameXml, timeLimitInSecs), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='gameXml'>
            /// </param>
            /// <param name='timeLimitInSecs'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<string> PostByGamexmlAndTimelimitinsecsAsync(this IChessAI operations, StringAux gameXml, int timeLimitInSecs, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PostByGamexmlAndTimelimitinsecsWithHttpMessagesAsync(gameXml, timeLimitInSecs, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
